config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id', to: 'tasks#show', as: :task
  get 'tasks/:id/edit', to: 'tasks#edit', as: :task_edit
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_permitted_params)
    @task.save
    redirect_to(tasks_path(@tasks))
  end

  def show
    id = params[:id]
    @tasks = Task.find(id)
  end

  def edit
    id = params[:id]
    @task = Task.find(id)
    @task.save
  end

  def update
    id = params[:id]
    @task = Task.find(id)
    @task.update(task_permitted_params)
    redirect_to(tasks_path(@tasks))
  end

  def destroy
    id = params[:id]
    @task = Task.find(id)
    @task.delete
    redirect_to tasks_path
  end

  private

  def task_permitted_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container">
<%= form_with model: @task do |f| %>
  <%= f.label :title, "Task Name" %>
  <%= f.text_field :title %>
  <%= f.label :details, "Task Details" %>
  <%= f.text_field :details %>
  <%= f.submit "Update Task"%>
<% end %>
</div>

app/views/tasks/index.html.erb
  <div class="container">
  <h1>My Tasks</h1>
  <ul>
        <% @tasks.each do |task| %>
       <li>
        <%= check_box_tag :completed %>
        <span><%= link_to task.title, task_path(task) %></span>
        <div class="btn btn-primary">
        <%= link_to "Edit", task_edit_path(task.id) %>
        </div>
        <div class="btn btn-danger">
        <%= link_to "Delete", task_path(task.id), data:{turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this task?"} %>
        </div>
      </li>
        <% end %>
    </ul>
  <div class="btn btn-warning"><%= link_to "New", tasks_new_path %></div>
</div>

app/views/tasks/new.html.erb
<div class="container ">
<%= form_with model: @task do |f| %>
  <%= f.label :title, "New task" %>
  <%= f.text_field :title %>
  <%= f.label :details, "Task Details" %>
  <%= f.text_field :details %>
  <%= f.submit "Add New Task" %>
<% end %>
</div>

app/views/tasks/show.html.erb
<div class="container">
<h1><%= @tasks.details %></h1>
<span class="btn btn-primary"><%= link_to 'Go Home', tasks_path(@tasks) %></span>
</div>